on: 
  release: 
    types: [published]

jobs:
  release-vocab-term:
    runs-on: ubuntu-20.04
    name: Releases the lit-term package
    steps:
     # Makes the current repository available to the workflow.
    - name: Checkout repo
      uses: actions/checkout@v2.1.0
      # Initializes node for the runner
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
        registry-url: 'https://registry.npmjs.org'
        scope: '@solid'
    - name: NPM install, test and publish
      run: |
        npm install
        npm test
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
